# Generated by Django 3.1.2 on 2020-10-28 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DRAFT', 'DRAFT'), ('PUBLISHED', 'PUBLISHED'), ('UNPUBLISHED', 'UNPUBLISHED')], default='PUBLISHED', max_length=30),
        ),
        migrations.AlterField(
            model_name='userbookmarks',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
